name: Release TSV

on:
  push:
    branches:
      - main
    paths:
      - 'tsv/*.tsv'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge TSV files
        run: |
          DATE=$(date +'%Y-%m-%d')
          OUTPUT="all_${DATE}.tsv"
      
          : > "$OUTPUT"

          find tsv -maxdepth 1 -type f -name "*.tsv" -print0 |
            while IFS= read -r -d '' file; do
              cat "$file" >> "$OUTPUT"
      
              # このファイルの末尾に改行を追加
              printf '\n' >> "$OUTPUT"
          done
      
          echo "OUTPUT=$OUTPUT" >> "$GITHUB_ENV"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "data-${{ github.run_number }}"
          name: "Dictionary ${{ env.OUTPUT }}"
          files: ${{ env.OUTPUT }}
          generate_release_notes: true
